# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb5514dc0ef409e35ea589c7924a8b4a2cc608d26f065d92b6187d5157030142e7747bdc20827fb9cab15c7d8739c39a18168313dc488318861c6e0f20f34ad3

test:
  secret_key_base: 1509a352011a488cf3cc134dcb01734ef6f4fcaaa3f233a5d83e1e27c96e3aed02a51de819c2f61cc3fe423bfb2276b25859597bf203467f1f4d19a3ea5ab188

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
